### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by cdupasquier1980** [mkhab7/deepai#1]
Hello,
I have a problem when I use your code.
Here is the error:
Fatal error: Uncaught Error: Call to undefined method Solid\Deepai\Deepai::colorize() in C:\wamp\www\colorize\index.php on line 14
( ! ) Error: Call to undefined method Solid\Deepai\Deepai::colorize() in C:\wamp\www\colorize\index.php on line 14

Can you help me, thanks in advance!

**Comment by mkhab7** [comment]
Hi ,could you give me your code and php version
